### ISSUE TITLE
Importing error on Blender 2.79

### ISSUE THREAD

**Issue by Teashrock** [joric/io_scene_b3d#2]
![image](https://user-images.githubusercontent.com/12483854/54082786-83765f00-4323-11e9-82b0-eabb868bad4a.png)

**Comment by joric** [comment]
Sorry haven't been notified (damn Microsoft). Could you link to a b3d model in question?

**Comment by Teashrock** [comment]
Finally here. Updated Blender to 2.80, got this:
![image](https://i.imgur.com/0qmIi6R.png)

**Comment by joric** [comment]
Didn't plan to deal with beta versions. Even the File menu looks entirely different. I'll look into a pull request if you figure this out.

**Upd**

Fixed `__init__.py` in a new 2.80 branch like this: https://github.com/joric/io_scene_b3d/commit/0cb975bb9ea31cb062eb104a55aa009e96ae9271

It's loaded but then there's still tons of errors on import.

```
material.diffuse_color = mat.rgba[:-1] # sequences of dimension 0 should contain 4 items, not 3
material.use_transparency = material.alpha < 1 # says no attribute material.alpha
mtex = material.texture_slots.add() # 'Material' object has no attribute texture_slots
ctx.scene.objects.link(ob) # bpy_prop_collection' object has no attribute 'link'
```
I have no idea how to fix that just yet. Even If I comment out color stuff the latter two things look like 2.80 has changed a lot, probably uses another namespace.

**Comment by Teashrock** [comment]
Ok, so for now I'll just use 2.79, then will report.

**Comment by Typhon306** [comment]
> Sorry haven't been notified (damn Microsoft). Could you link to a b3d model in question?

https://cdn.discordapp.com/attachments/376132246161326081/530024057291276288/gooey.b3d

It's not the file from Teashrock, but I guess the problem's the same

**Comment by joric** [comment]
@Typhon306 cool, thanks. I'm busy now, could take a while.

**Comment by joric** [comment]
Updated a bunch of things here 541a1b07, your file loads now. Textures may be missing but it's an another 2.8 migrating-related issue.
