### ISSUE TITLE
Add-On not found

### ISSUE THREAD

**Issue by Typhon306** [joric/io_scene_b3d#3]
Hi, I've got another problem with your files... When I applied "Install Add-On from file", Blender reported me a successful installation...

![Issue](https://user-images.githubusercontent.com/51017277/59263256-f9e76d80-8c40-11e9-9bd4-81d5adb3725d.png)

But I couldn't find it in the Add-On list. Did I do anything wrong?

**Comment by joric** [comment]
Github snapshots (io_scene_b3d-master.zip) don't have proper structure for blender. There are two nested directories, it should be only one. Repack the io_scene_b3d directory into a separate zip.
