### ISSUE TITLE
Exported .B3D Models crash in Blitz3D/OpenB3D/MiniB3D

### ISSUE THREAD

**Issue by Kippykip** [joric/io_scene_b3d#5]
Yeah so the exporter appears to be broken (even when I go way back into old blender builds and the original gandalf releases etc).
Surprisingly the models import fine with the animation and everything within fragMOTION, but as far as I know everything else that uses the .B3D model format crashes.

**Comment by joric** [comment]
Yeah fragMOTION rules, I use fragMOTION. Hell knows what's happened with GaNDaLDF releases, they should work if you rollback all the software.
