### ISSUE TITLE
Can you please mike it import the animations of the model, too?

### ISSUE THREAD

**Issue by Drachenbauer** [joric/io_scene_b3d#6]
Hello

I´m modifying character-models in an open source-game.
But some of them ar only saved in .b3d in their model-folders.
No .blend-models there for theese ones.

Now i notices, that import from.b3d imports no character-animations.
Can you please add this feature to this tool?

**Comment by joric** [comment]
Yeah I'll look into it. I tried to import animation but math is pretty complicated. It's almost there but it's commented out for now maybe someone could make it work. I'm a little bit busy for the next couple of months.

**Comment by Foxar** [comment]
Yeah, there's literally no way as far as I know to convert b3d models to modern file formats including animations. I need to convert some models for a Unity project and hoped this tool would help me out but no luck as I need animations.

**Comment by joric** [comment]
@Foxar I converted most of my models with fragmotion  http://www.fragmosoft.com

**Comment by Foxar** [comment]
Fragmotion doesn't allow to export to any modern formats though, none compatible with unity or blender.

**Comment by joric** [comment]
@Foxar I used export to SMD and then to whatever I wanted, it's in the readme. The only problem is that it's a nasty nagware but I managed.

**Comment by Foxar** [comment]
When I use fragmotion to export to SMD it requires to choose if im exporting mesh or animation, meaning I can't do both no?

**Comment by joric** [comment]
Maybe export both and merge them i don't remember really. I used fragmotion export for all the animated models here https://github.com/joric/gnome

**Comment by Kippykip** [comment]
Fragmotion import B3D>export to MS3D
Blender>import MS3D
there

**Comment by Foxar** [comment]
Blender does not support importing ms3d.

**Comment by Kippykip** [comment]
> Blender does not support importing ms3d.  

It absolutely does but you have to enable the importer/exporter in the options as it's not enabled by default.
Tested in Blender 2.79b and Bforartists 1.0.0

**Comment by joric** [comment]
Stalled
