### ISSUE TITLE
All meshes are exported, even if the object is deleted.

### ISSUE THREAD

**Issue by Poikilos** [joric/io_scene_b3d#7]
The add-on appears to search the entire blender scene for meshes. If you make two objects and delete one, they both get exported.
![screenshot_20200212_112108](https://user-images.githubusercontent.com/7557867/75209133-842e1e00-574b-11ea-89e6-bd66153d41a8.png)

- The screenshot is from my fork of prestibags: <https://github.com/poikilos/prestibags>
- You may also want to respect the "Selection Only" export checkbox, or split that into another issue. If you fix that first, it would mitigate this issue.

Good work on the plugin so far! I am glad that I can use Blender 2.8 for Minetest models.

**Comment by Poikilos** [comment]
@joric, did you get this?

**Comment by joric** [comment]
yeah i don't have time for this. fix it and submit pr

**Comment by Poikilos** [comment]
Hi, see https://github.com/VirtualBrightPlayz/io_scene_b3d

**Comment by Poikilos** [comment]
@joric Consider disabling issues and putting a deprecation notice list of forks in the GitHub project description and/or readme. That way people know where to get the fixes and support that exist. You could also set the repo settings in GitHub to "archived".

**Comment by joric** [comment]
No, thank you.
